image:
  file: .gitpod.Dockerfile
tasks:
  - init: ''
    command: 'echo "Strat CVeno: deno run --allow-net --allow-env --allow-read main.js"'

vscode:
  extensions:
    - denoland.vscode-deno@2.3.1:EQc/TzIQd+H8BcYsPXTo/A==
